repos:
- hooks:
  - entry: 	./scripts/format.sh
    id: clang-format
    language: system
    name: Run clang-format

  - entry: 	./scripts/lint.sh
    id: clang-tidy
    language: system
    name: Run clang-tidy

  repo: local

- hooks:
  - id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0

- repo: https://github.com/commitizen-tools/commitizen
  rev: master
  hooks:
    - id: commitizen
      stages: [push]
