repos:
- hooks:
  - entry: clang-format -i
    files: ^.+\.[ch]$
    id: clang-format
    language: system
    name: Run clang-format

  - entry: clang-tidy  --config-file .clang-tidy
    types: [c]
    id: clang-tidy
    language: system
    name: Run clang-tidy

  repo: local
- hooks:
  - id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
